<?php

namespace App\Models\Forms;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\TaxReturn;

class Income extends Model
{
    use HasFactory;

    protected $fillable = [
        'tax_return_id',
        'employer_abn',
        'total_tax_withheld',
        'gross_payments',
        'income_items',
        'allowances',
        'fringe_benefits',
        'reportable_super',
        'account_holders',
        'interest_tax_withheld',
        'total_interest',
        'dividend_account_holders',
        'unfranked_amount',
        'franked_amount',
        'franking_credits',
        'dividend_tax_withheld',
        'allowance_tax_withheld',
        'allowance_total_received',
        'pension_tax_withheld',
        'pension_total_received',
        'etp_tax_withheld',
        'etp_taxable_component',
        'etp_code',
        'etp_abn',
        'payment_start_day',
        'payment_start_month',
        'payment_start_year',
        'payment_end_day',
        'payment_end_month',
        'payment_end_year',
        'tax_withheld',
        'taxable_taxed',
        'taxable_untaxed',
        'tax_offset',
        'lump_day',
        'lump_month',
        'lump_year',
        'taxed_component',
        'untaxed_component',
        'tax_free_component',
        'payer_abn',
        'discount_upfront_eligible',
        'discount_upfront_not_eligible',
        'discount_deferral',
        'tfn_withheld',
        'foreign_discounts',
        'foreign_tax_paid',
        'foreign_income_type',
        'foreign_income_other',
        'deductible_expenses',
        'gross_amount',
        'nz_franking_credit',
        'pension_type',
        'gross_amount_pension',
        'deductible_expenses_pension',
        'undeducted_purchase_price',
        'foreign_tax_paid_pension',
        'employment_gross_amount',
        'employment_income_description',
        'foreign_income_country',
        'foreign_income_occupation',
        'foreign_income_gross_amount',
        'other_income_type',
        'other_income_amount',
        'bal_adj_financial',
        'bal_adj_rental',
        'bal_adj_remaining',
        'only_income',
        'only_income_details',
        'rollover_code',
        'foreign_credit',
        'gain_discount_eligible',
        'gain_not_discounted',
        'cgt_attachment',
        'etp_attachment',
        'street',
        'suburb',
        'state',
        'postcode',
        'rental_file',
        'partnership_name',
        'trust_name',
        'distribution_partnerships',
        'distribution_partnerships_result',
        'distribution_trusts',
        'distribution_trusts_result',
        'distribution_trusts_code',
        'other_distribution_deduction_type',
        'nonpp_action_code',
        'nonpp_other_deductions_type',
        'trust_tax_reason',
        'partner_credit_abn',
        'trust_credit_abn',
        'partner_closely_held_tfn',
        'trust_closely_held_tfn',
        'under60_details',
        'net_business_type',
        'rental_business_type',
        'other_income_15_type',
        'tax_withheld_abn',
        'lump_sum_count',
        'managed_fund_count',
        'rental_property_count',
        'etp_day',
        'etp_month',
        'etp_year',
        'start_day',
        'start_month',
        'start_year',
        'weeks_rented',
        'current_year_losses',
        'prior_year_losses',
        'cg_listed_shares_gain',
        'cg_listed_shares_loss',
        'cg_other_shares_gain',
        'cg_other_shares_loss',
        'cg_listed_units_gain',
        'cg_listed_units_loss',
        'cg_other_units_gain',
        'cg_other_units_loss',
        'cg_real_estate_au_gain',
        'cg_real_estate_au_loss',
        'cg_other_real_estate_gain',
        'cg_other_real_estate_loss',
        'cg_other_assets_gain',
        'cg_other_assets_loss',
        'cg_super_deferred_gain',
        'cg_super_deferred_loss',
        'ownership_percentage',
        'rental_income',
        'other_income',
        'council_rates',
        'interest_loans',
        'agent_fees',
        'repairs',
        'body_corp',
        'water_charges',
        'capital_allowance',
        'capital_works',
        'advertising',
        'gardening',
        'insurance',
        'land_tax',
        'legal_fees',
        'pest_control',
        'stationery',
        'travel_expenses',
        'sundry',
        'landcare_deduction',
        'deduction_partnership',
        'deduction_trusts',
        'nonpp_dist_partnerships_investment',
        'nonpp_profit_loss_1',
        'nonpp_net_rental_income',
        'nonpp_profit_loss_2',
        'nonpp_other_dist_partnerships',
        'nonpp_profit_loss_3',
        'nonpp_managed_income',
        'nonpp_profit_loss_4',
        'nonpp_other_trusts_income',
        'nonpp_profit_loss_5',
        'nonpp_franked_investments',
        'nonpp_franked_other',
        'nonpp_landcare_exp',
        'nonpp_managed_deductions',
        'nonpp_partnership_deduction_o',
        'nonpp_partnership_deduction_rent_o',
        'nonpp_other_deduction_o',
        'nonpp_other_deduction_uc',
        'partner_smallbiz_income',
        'trust_smallbiz_income',
        'share_trust_income',
        'trust_tax_credit',
        'partner_franking_credit',
        'trust_franking_credit',
        'partner_tfn_credit',
        'trust_tfn_credit',
        'partner_foreign_credit',
        'trust_foreign_credit',
        'partner_nras_offset',
        'trust_nras_offset',
        'annuity_tax_withheld',
        'annuity_total_received',
        'net_business',
        'rental_business',
        'other_income_15',
        'small_business_income',
        'tax_withheld_voluntary',
        'foreign_withholding',
        'partnership_investing',
        'partnership_rental',
        'partnership_other',
        'partnership_total',
        'sole_investing',
        'sole_rental',
        'sole_other',
        'sole_total',
        'primary_production',
        'non_primary_production',
        'fhss_amount',
        'fhss_tax_withheld',
        'professional_income',
        'cgt_concession_active',
        'cgt_concession_retirement',
        'cgt_concession_rollover',
        'psi_voluntary_agreement',
        'psi_abn_not_quoted',
        'psi_labour_hire',
        'labour_hire',
        'credit_paid_by_trustee',
    ];

    protected $casts = [
        'employer_abn' => 'array',
        'total_tax_withheld' => 'array',
        'gross_payments' => 'array',
        'income_items' => 'array',
        'allowances' => 'array',
        'fringe_benefits' => 'array',
        'reportable_super' => 'array',
        'account_holders' => 'array',
        'interest_tax_withheld' => 'array',
        'total_interest' => 'array',
        'dividend_account_holders' => 'array',
        'unfranked_amount' => 'array',
        'franked_amount' => 'array',
        'franking_credits' => 'array',
        'dividend_tax_withheld' => 'array',
        'allowance_tax_withheld' => 'array',
        'allowance_total_received' => 'array',
        'pension_tax_withheld' => 'array',
        'pension_total_received' => 'array',
        'etp_tax_withheld' => 'array',
        'etp_taxable_component' => 'array',
        'etp_code' => 'array',
        'etp_abn' => 'array',
        'payment_start_day' => 'array',
        'payment_start_month' => 'array',
        'payment_start_year' => 'array',
        'payment_end_day' => 'array',
        'payment_end_month' => 'array',
        'payment_end_year' => 'array',
        'tax_withheld' => 'array',
        'taxable_taxed' => 'array',
        'taxable_untaxed' => 'array',
        'tax_offset' => 'array',
        'lump_day' => 'array',
        'lump_month' => 'array',
        'lump_year' => 'array',
        'taxed_component' => 'array',
        'untaxed_component' => 'array',
        'tax_free_component' => 'array',
        'payer_abn' => 'array',
        'discount_upfront_eligible' => 'array',
        'discount_upfront_not_eligible' => 'array',
        'discount_deferral' => 'array',
        'tfn_withheld' => 'array',
        'foreign_discounts' => 'array',
        'foreign_tax_paid' => 'array',
        'foreign_income_type' => 'array',
        'foreign_income_other' => 'array',
        'deductible_expenses' => 'array',
        'gross_amount' => 'array',
        'nz_franking_credit' => 'array',
        'pension_type' => 'array',
        'gross_amount_pension' => 'array',
        'deductible_expenses_pension' => 'array',
        'undeducted_purchase_price' => 'array',
        'foreign_tax_paid_pension' => 'array',
        'employment_gross_amount' => 'array',
        'employment_income_description' => 'array',
        'foreign_income_country' => 'array',
        'foreign_income_occupation' => 'array',
        'foreign_income_gross_amount' => 'array',
        'other_income_type' => 'array',
        'other_income_amount' => 'array',
        'bal_adj_financial' => 'array',
        'bal_adj_rental' => 'array',
        'bal_adj_remaining' => 'array',
        'cgt_concession_active' => 'boolean',
        'cgt_concession_retirement' => 'boolean',
        'cgt_concession_rollover' => 'boolean',
        'psi_voluntary_agreement' => 'boolean',
        'psi_abn_not_quoted' => 'boolean',
        'psi_labour_hire' => 'boolean',
        'labour_hire' => 'boolean',
        'credit_paid_by_trustee' => 'boolean',
    ];

    public function taxReturn()
    {
        return $this->belongsTo(TaxReturn::class);
    }
}
